<h5>Preferencias del sistema</h5>
<ul>
	<li><a href="/cgi-bin/koha/admin/systempreferences.pl">Preferencias del sistema</a></li>
</ul>

<h5>Par&aacute;metros b&aacute;sicos</h5>
<ul>
	<li><a href="/cgi-bin/koha/admin/branches.pl">Libraries and groups</a></li>
	<li><a href="/cgi-bin/koha/admin/aqbookfund.pl">Fondos y presupuestos</a></li>
	<li><a href="/cgi-bin/koha/admin/currency.pl">Monedas y tipo de cambio</a></li>
	<li><a href="/cgi-bin/koha/admin/itemtypes.pl">Item types</a></li>
</ul>

<h5>Socios y ciculación</h5>
<ul>
	<li><a href="/cgi-bin/koha/admin/categorie.pl">Tipos y categorías de socio</a></li>
	<li><a href="/cgi-bin/koha/admin/cities.pl">Ciudades y pueblos</a></li>
	<li><a href="/cgi-bin/koha/admin/roadtype.pl">Tipos de camino</a></li>
	<li><a href="/cgi-bin/koha/admin/patron-attr-types.pl">Tipos de atributo de socio</a></li>
	<li><a href="/cgi-bin/koha/admin/smart-rules.pl">Reglas de circulación y multas</a></li>
	<li><a href="/cgi-bin/koha/admin/branch_transfer_limits.pl">Library transfer limits</a></li>
	<li><a href="/cgi-bin/koha/admin/item_circulation_alerts.pl">Item circulation alerts</a></li>
	<li><a href="/cgi-bin/koha/admin/itemstatus.pl">Other item status</a></li>
</ul>

<h5>Cat&aacute;logo</h5>
<ul>
	<li><a href="/cgi-bin/koha/admin/authorised_values.pl">Valores autorizados</a></li>
	<li><a href="/cgi-bin/koha/admin/biblio_framework.pl">Hojas de trabajo bibliográficas MARC</a></li>
	<li><a href="/cgi-bin/koha/admin/koha2marclinks.pl">Correspondencia Koha - MARC</a></li>
	<li><a href="/cgi-bin/koha/admin/checkmarc.pl">Prueba de las hojas de trabajo bibliográficas MARC</a></li>
    <li><a href="/cgi-bin/koha/admin/authtypes.pl">Tipos de autoridad</a></li>
    <li><a href="/cgi-bin/koha/admin/classsources.pl">Fuentes de clasificaci&oacute;n</a></li>
    <li><a href="/cgi-bin/koha/admin/matching-rules.pl">Regla de coincidencia de registro</a></li>
</ul>

<h5>Par&aacute;metros adicionales</h5>

<ul>
	<!-- TMPL_IF NAME="NoZebra" --><li><a href="/cgi-bin/koha/admin/stopwords.pl">Palabras eliminadas </a></li><!-- /TMPL_IF -->
	<!-- <li><a href="/cgi-bin/koha/admin/printers.pl">Network Printers</a></li> -->
	<li><a href="/cgi-bin/koha/admin/z3950servers.pl">Clientes Z39.50</a></li>
</ul>
