<br clear="all" />

<div class="center">
<a href="/cgi-bin/koha/mainpage.pl">Inicio</a> ||
<a href="/cgi-bin/koha/catalogue/search.pl">Cat&aacute;logo</a> ||
<a href="/cgi-bin/koha/members/members-home.pl">Miembros</a> ||
<a href="/cgi-bin/koha/acqui/acqui-home.pl">Adquisiciones</a> ||
<a href="/cgi-bin/koha/circ/circulation.pl">Circulaci&oacute;n</a> ||
<a href="/cgi-bin/koha/reports-home.pl">Informes</a> ||
<a href="/cgi-bin/koha/admin-home.pl">Par&aacute;metros</a> ||
<a href="/cgi-bin/koha/about.pl">Acerca de Koha</a> || 
Ayuda
</div>

</body>
</html>
