<h5>Crear y generar informes</h5>
<ul>
	<li><a href="/cgi-bin/koha/reports/guided_reports.pl?phase=Build%20new">Crear nuevo</a></li>
	<li><a href="/cgi-bin/koha/reports/guided_reports.pl?phase=Use%20saved">Usar guardado</a></li>
	<li><a href="/cgi-bin/koha/reports/guided_reports.pl?phase=Create%20report%20from%20SQL">Crear a partir de SQL</a></li>
</ul>
<h5>Diccionario de informes</h5>
<ul>
<li><a href="/cgi-bin/koha/reports/dictionary.pl?phase=View%20Dictionary">Ver diccionario</a></li>
</ul>
