<h5>Informes guiados</h5>
	<ul>
		<li><a href="/cgi-bin/koha/reports/guided_reports.pl">Informes guiados</a></li>
	</ul>

<h5>Estad&iacute;sticas Compuestas</h5>
	<ul>
		<li><a href="/cgi-bin/koha/reports/acquisitions_stats.pl">Adquisiciones</a></li>
		<li><a href="/cgi-bin/koha/reports/borrowers_stats.pl">Socios</a></li>
		<li><a href="/cgi-bin/koha/reports/catalogue_stats.pl">Cat&aacute;logo</a></li>
		<li><a href="/cgi-bin/koha/reports/issues_stats.pl">Circulaci&oacute;n</a></li>
                <li><a href="/cgi-bin/koha/reports/serials_stats.pl">Publicaciones periódicas</a></li>
	</ul>


	<h5>Listas principales</h5>
	<ul>
		<li><a href="/cgi-bin/koha/reports/bor_issues_top.pl">Socios con más préstamos</a></li>
		<li><a href="/cgi-bin/koha/reports/cat_issues_top.pl">Items m&aacute;s prestados</a></li>
	</ul>
	
	<h5>Inactivo</h5>
	<ul>
		<li><a href="/cgi-bin/koha/reports/borrowers_out.pl">Socios que no han pedido prestado</a></li>
		<li><a href="/cgi-bin/koha/reports/catalogue_out.pl">Items nunca prestados</a></li>
	</ul>


	<h5>Otro</h5>
	<ul>
		<li><a href="/cgi-bin/koha/reports/itemslost.pl">Items perdido</a></li>
		<li><a href="/cgi-bin/koha/reports/manager.pl?report_name=itemtypes">Cat&aacute;logo por tipo de ítem</a></li>
		<li><a href="/cgi-bin/koha/reports/issues_avg_stats.pl">Tiempo de pr&eacute;stamo promedio</a></li>
		<li><a href="/cgi-bin/koha/reports/expiredholds.pl">Expired Holds</a></li>
		<li><a href="/cgi-bin/koha/reports/cancelledholds.pl">Cancelled Holds</a></li>
	</ul>
