    <fieldset>
    <legend>Campos codificados</legend>
    <p>
    <label>Audiencia</label>
    <select name="limit" class="subtype">
            <option value="" SELECTED="selected" >Cualquier</option>
      <option value="aud:a">juvenil, general</option>
      <option value="aud:b">pre-escolar (0-5)</option>
      <option value="aud:c">Primaria (5-8)</option>
      <option value="aud:d">niños (9-14)</option>
      <option value="aud:e">Adulto joven</option>
      <option value="aud:k">Adulto, serio</option>
      <option value="aud:m">Adulto, General</option>
      <option value="aud:u">Desconocido</option>
    </select>
    </p>
    <p>
    <label>Imprimir</label>
        <select name="limit" class="subtype">
      <option value="" selected="selected" >cualquiera</option>
        <option value="Material-type:r">impresión regular</option>
        <option value="Material-type:d">impresión grande</option>
        <option value="Material-type:e">formato de períodico</option>
        <option value="Material-type:f">Braille o escritura lunar</option>
        <option value="Material-type:g">micro impreso</option>
        <option value="Material-type:h">escrito a mano</option>
        <option value="Material-type:i">multimedia</option>
        <option value="Material-type:j">mini-impreso</option>
        <option value="Material-type:z">otra forma de material textual</option>
    </select>
    </p>
    <p>
    <label>Feschrift Ind.</label>
    <select name="limit" class="subtype">
      <option value="" selected="selected" >Cualquier</option>
            <option value="Literature-Code:a">ficción</option>
            <option value="Literature-Code:b">drama</option>
            <option value="Literature-Code:c">ensayos</option>
            <option value="Literature-Code:d">humor, sátira</option>
            <option value="Literature-Code:e">cartas</option>
            <option value="Literature-Code:f">historias cortas</option>
            <option value="Literature-Code:g">poesía</option>
            <option value="Literature-Code:h">discursos, oratoria</option>
            <option value="Literature-Code:y">no es un texto literario</option>
            <option value="Literature-Code:z">multiple/otras formas literarias </option>
    </select>
    </p>
        <p>
    <label>Bibliografía</label>
        <select name="limit" class="subtype" size="1">
            <option value="">Cualquier</option>
            <option value="Biography-code:y">No es una biografía</option>
            <option value="Biography-code:a">autobiografía</option>
            <option value="Biography-code:b">biografía individual</option>
            <option value="Biography-code:c">biografía colectiva</option>
            <option value="Biography-code:d">contiene datos biograficos</option>
    </select>
        </p>
        <p>
    <label>Ilustración</label>
        <select name="limit" class="subtype" size="1">
            <option value="">Cualquier</option>
            <option value="Illustration-Code:a">ilustraciones</option>
            <option value="Illustration-Code:b">mapas</option>
            <option value="Illustration-Code:c">retratos</option>
            <option value="Illustration-Code:d">cartas</option>
            <option value="Illustration-Code:e">planes</option>
            <option value="Illustration-Code:f">placas</option>
            <option value="Illustration-Code:g">música</option>
            <option value="Illustration-Code:h">facsímiles</option>
            <option value="Illustration-Code:i">escudos de armas</option>
            <option value="Illustration-Code:j">tablas genealógicas</option>
            <option value="Illustration-Code:k">formularios</option>
            <option value="Illustration-Code:l">muestras</option>
            <option value="Illustration-Code:m">grabaciones de sonido</option>
            <option value="Illustration-Code:n">transparencias</option>
            <option value="Illustration-Code:o">iluminaciones</option>
            <option value="Illustration-Code:y">sin ilustraciones</option>
        </select>
        </p>
    <p>
    <label>Contenido</label>
    <select name="limit" class="subtype">
      <option value="" >Cualquier</option>
            <option value="ctype:a" >bibliografia</option>
            <option value="ctype:b" >catálogo</option>
            <option value="ctype:c" >índice</option>
            <option value="ctype:d" >resumen</option>
            <option value="ctype:e" >diccionario</option>
            <option value="ctype:f" >enciclopedia</option>
            <option value="ctype:g" >directorio</option>
            <option value="ctype:h" >descripción de proyecto</option>
            <option value="ctype:i" >estadísticas</option>
            <option value="ctype:j" >libros de texto programados</option>
            <option value="ctype:k" >patente</option>
            <option value="ctype:l" >estándar</option>
            <option value="ctype:m" >disertación o tesis</option>
            <option value="ctype:n" >leyes y legislación</option>
            <option value="ctype:o" >tabla numérica</option>
            <option value="ctype:p" >informe técnico</option>
            <option value="ctype:q" >trabajo de examinación</option>
            <option value="ctype:r" >repasos/críticas literiarias</option>
            <option value="ctype:s" >tratados</option>
            <option value="ctype:t" >historietas o cómics</option>
            <option value="ctype:z" >otro</option>
    </select>
        </p>
        <p>
    <label>Tipos de Video</label>
    <select name="limit" class="subtype">
            <option value="">Cualquier</option>
      <option value="Video-mt:a">cine</option>
      <option value="Video-mt:b">proyección visual</option>
      <option value="Video-mt:c">grabación de vídeo</option>
    </select>
        </p>
    </fieldset>
    <fieldset>
    <legend>Publicaciones periódicas</legend><p>
    <p>
    <label>Tipo de publicación periódica</label>
    <select name="limit" class="subtype">
           <option value="">Cualquier tipo</option>
           <option value="Type-Of-Serial:a">Periódico</option>
      <option value="Type-Of-Serial:b">Series monográficas</option>
      <option value="Type-Of-Serial:c">Periodico</option>
      <option value="Type-Of-Serial:z">Otro</option>
    </select>
    </p>
    <p>
    <label>Periodicidad</label>
    <select name="limit" class="subtype">
      <option value="">Cualquier</option>
        <option value="Frequency-code:a">Diario</option>
        <option value="Frequency-code:b">Bisemanal</option>
        <option value="Frequency-code:c">Semanal</option>
        <option value="Frequency-code:d">Bisemanal</option>
        <option value="Frequency-code:e">Bimensual</option>
        <option value="Frequency-code:f">Mensual</option>
        <option value="Frequency-code:g">Bimensual</option>
        <option value="Frequency-code:h">Trimestral</option>
        <option value="Frequency-code:i">Tres veces al año</option>
        <option value="Frequency-code:j">Semi anual</option>
        <option value="Frequency-code:k">Anual</option>
        <option value="Frequency-code:l">Bianual</option>
        <option value="Frequency-code:m">Trienal</option>
        <option value="Frequency-code:n">Tres veces a la semana</option>
        <option value="Frequency-code:o">Tres veces al mes</option>
        <option value="Frequency-code:u">Desconocido</option>
        <option value="Frequency-code:y">Sin periodicidad</option>
        <option value="Frequency-code:i">Otro</option>
    </select>
    </p>
    <p>
    <label>Regularidad</label>
    <select name="limit" class="subtype">
            <option value="">Cualquier regularidad</option>
        <option value="Regularity-code:u">Desconocido</option>
        <option value="Regularity-code:a">Regular</option>
        <option value="Regularity-code:b">Irregular normalizado</option>
        <option value="Regularity-code:y">irregular</option>
    </select>
        </p>

        </fieldset>
    <fieldset>
    <legend>Imagen</legend><p>
    <select name="limit" class="subtype">
        <option value="">Cualquier</option>
        <option value="Graphics-type:a">collage</option>
        <option value="Graphics-type:b">dibujo</option>
        <option value="Graphics-type:c">pintura</option>
        <option value="Graphics-type:d">reproducción fotomecánica</option>
        <option value="Graphics-type:e">negativo fotográfico</option>
        <option value="Graphics-type:f">photoprint</option>
        <option value="Graphics-type:h">imagen</option>
        <option value="Graphics-type:i">imprimir</option>
        <option value="Graphics-type:k">dibujo técnico</option>
        <option value="Graphics-type:z">otro tipo de gráfico no proyectado</option>
    </select>
    <select name="limit" class="subtype">
            <option value="">cualquiera</option>
            <option value="Graphics-support:a">lienzo</option>
            <option value="Graphics-support:b">papel bristol</option>
            <option value="Graphics-support:c">cartón/ilustración</option>
            <option value="Graphics-support:d">cristal</option>
            <option value="Graphics-support:j">yeso</option>
            <option value="Graphics-support:k">tabla base</option>
            <option value="Graphics-support:l">porcelana</option>
            <option value="Graphics-support:m">piedra</option>
            <option value="Graphics-support:n">madera</option>
            <option value="Graphics-support:u">desconocido</option>
            <option value="Graphics-support:v">colección mixta</option>
            <option value="Graphics-support:e">sintéticos</option>
            <option value="Graphics-support:f">piel</option>
            <option value="Graphics-support:g">textil</option>
            <option value="Graphics-support:h">metal</option>
            <option value="Graphics-support:i">papel</option>
            <option value="Graphics-support:z">otros</option>
    </select>
        </p>
