<option value="score desc">Relevance</option>
<optgroup label="Popularity">
<option value="popularity desc">Popularity (Most to Least)</option>
<option value="popularity asc">Popularity (Least to Most)</option>
</optgroup>
<optgroup label="Author">
<option value="author-sort asc">Author (A-Z)</option>
<option value="author-sort desc">Author (Z-A)</option>
</optgroup>
<optgroup label="Call Number">
<option value="cn-sort asc">Call Number (Non-fiction 0-9 to Fiction A-Z)</option>
<option value="cn-sort desc">Call Number (Fiction Z-A to Non-fiction 9-0)</option>
</optgroup>
<optgroup label="Dates">
<option value="pubyear desc">Publication/Copyright Date: Newest to Oldest</option>
<option value="pubyear asc">Publication/Copyright Date: Oldest to Newest</option>
<option value="acqdate desc">Acquisition Date: Newest to Oldest</option>
<option value="acqdate asc">Acquisition Date: Oldest to Newest</option>
</optgroup>
<optgroup label="Title">
<option value="title-sort asc">Title (A-Z)</option>
<option value="title-sort desc">Title (Z-A)</option>
</optgroup>

